apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: plhgg9no0-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/plhgg9no0-java-quarkus-gitops